# pull official base image
FROM python:3.10-alpine

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

# install psycopg2
RUN apk update \
    && apk add --virtual build-essential gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    && pip install psycopg2

# install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.test.sh
COPY ./entrypoint.test.sh .
RUN sed -i 's/\r$//g' ./entrypoint.test.sh
RUN chmod +x ./entrypoint.test.sh

# copy project
COPY . .

# add and run as non-root user
RUN adduser -D myuser
USER myuser

# run entrypoint.sh
ENTRYPOINT ["./entrypoint.test.sh"]